# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build steps
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test phase
        run: echo "Running test cases"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "Deploying the app"
  

